# Generated by Django 6.0.7 on 2026-07-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='property_gallery/'),
        ),
    ]
