# Generated by Django 6.0.7 on 2026-07-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='expected_move_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='interested_for',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], default='Buy', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Visited', 'Visited'), ('Booked', 'Booked'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
